[package]
name    = "rustsec-website-gen"
version = "0.0.0"
authors = ["Tony Arcieri <bascule@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
handlebars = "2"
rustsec = "0.13"
serde = { version = "1", features = ["serde_derive"] }
